# "org" ensures this Service is used with the correct Serverless Framework Access Key
useDotenv: true

org: koeppster
service: box-event-skill

plugins:
  - serverless-dotenv-plugin

# before you deploy your app, you should set credential with the follow cmd:
# serverless config credentials --provider aws --key $AWS_KEY$ --secret $AWS_SECRET$ -o
provider:
  name: aws
  runtime: nodejs18.x
  timeout: 10 # server should still acknowledge Box skills engine within 10 seconds of receiving the event
  versionFunctions: true # maintains past versions in single deployment
  environment:
    box_primary_key: ${env:BOX_PRIMARY_KEY}
    box_secondary_key: ${env:BOX_SECONDARY_KEY}
    box_api_endpoint: "https://api.box.com/2.0"

# overwriting defaults
#  stage: ${opt:stage, 'dev'}
  region: us-east-1

# packaging information
package:
    exclude:
        - .gitignore
        - .git/**

functions:
  skill:
    handler: index.handler
    events: # The Events that trigger this Function
      - http:
          path: ${self:service}
          method: any
